-- CLIENTES

-- SP, CURSORES DE SISTEMA Y CURSOR Y VSQL PARA OBTENER CLIENTES

ALTER TABLE CLIENTES ADD ESTADO NUMBER(1) DEFAULT 1 NOT NULL;

create or replace PROCEDURE Obtener_Clientes (DATOS OUT SYS_REFCURSOR)
AS
    VSQL VARCHAR2(2000);
BEGIN
    VSQL := 'SELECT 
    C.ID_CLIENTE,
    C.NOMBRE,
    C.APELLIDO_PATERNO,
    C.APELLIDO_MATERNO,
    C.EDAD,
    C.EMAIL,
    C.TELEFONO,
    M.NOMBRE AS Nombre_Membresia
    FROM CLIENTES C
    INNER JOIN Membresias M ON M.ID_MEMBRESIA = C.ID_MEMBRESIA
    WHERE C.ESTADO = 1
    ORDER BY C.ID_CLIENTE ASC';

    OPEN DATOS FOR VSQL;
END;

-- SP PARA ELIMINAR CLIENTE

CREATE OR REPLACE PROCEDURE Eliminar_Cliente (ID_CLIENTE IN NUMBER)
AS
    VSQL VARCHAR2(2000);
BEGIN
    VSQL := 'UPDATE CLIENTES SET ESTADO = 0
             WHERE ID_CLIENTE = :P1';
    EXECUTE IMMEDIATE VSQL USING ID_CLIENTE;
END;

-- SP PARA OBTENER CLIENTE POR ID

CREATE OR REPLACE PROCEDURE Obtener_Cliente_Por_ID (ID_CLIENTE IN NUMBER, DATOS OUT SYS_REFCURSOR)
AS
    VSQL VARCHAR2(2000);
BEGIN
    VSQL := 'SELECT 
    C.ID_CLIENTE,
    C.NOMBRE,
    C.APELLIDO_PATERNO,
    C.APELLIDO_MATERNO,
    C.EDAD,
    C.EMAIL,
    C.TELEFONO,
    M.NOMBRE AS Nombre_Membresia
    FROM CLIENTES C
    INNER JOIN Membresias M ON M.ID_MEMBRESIA = C.ID_MEMBRESIA
    WHERE C.ID_CLIENTE = :P1';
    OPEN DATOS FOR VSQL USING ID_CLIENTE;
END;

-- Metodo para actualizar cliente por ID

CREATE OR REPLACE PROCEDURE Actualizar_Cliente (
    V_ID_CLIENTE IN NUMBER, 
    V_NOMBRE IN VARCHAR2, 
    V_APELLIDO_PATERNO IN VARCHAR2, 
    V_APELLIDO_MATERNO IN VARCHAR2, 
    V_EDAD IN NUMBER, 
    V_EMAIL IN VARCHAR2, 
    V_TELEFONO IN VARCHAR2, 
    V_ID_MEMBRESIA IN NUMBER)
AS
BEGIN
    UPDATE CLIENTES SET 
    NOMBRE = V_NOMBRE,
    APELLIDO_PATERNO = V_APELLIDO_PATERNO,
    APELLIDO_MATERNO = V_APELLIDO_MATERNO,
    EDAD = V_EDAD,
    EMAIL = V_EMAIL,
    TELEFONO = V_TELEFONO,
    ID_MEMBRESIA = V_ID_MEMBRESIA
    WHERE ID_CLIENTE = V_ID_CLIENTE;
END;

-- metodo para ingresar cliente

CREATE OR REPLACE PROCEDURE Ingresar_Cliente (
    V_NOMBRE IN VARCHAR2, 
    V_APELLIDO_PATERNO IN VARCHAR2, 
    V_APELLIDO_MATERNO IN VARCHAR2, 
    V_EDAD IN NUMBER, 
    V_EMAIL IN VARCHAR2, 
    V_TELEFONO IN VARCHAR2, 
    V_ID_MEMBRESIA IN NUMBER)
AS
BEGIN
    INSERT INTO CLIENTES (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, EDAD, EMAIL, TELEFONO, ID_MEMBRESIA, ESTADO)
    VALUES (V_NOMBRE, V_APELLIDO_PATERNO, V_APELLIDO_MATERNO, V_EDAD, V_EMAIL, V_TELEFONO, V_ID_MEMBRESIA, 1);
END;
